# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='tasks',
            field=models.ManyToManyField(through='course.AssignmentTask', to='course.Task'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
