# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170815_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
