# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 22:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_grade_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='ranking_size',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Canceled'),
        ),
    ]
