# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('markdown_text', models.TextField()),
                ('html_code', models.TextField(blank=True)),
                ('post_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_pinned_to_the_top', models.BooleanField(default=False)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseClass')),
            ],
        ),
    ]
