# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='percentage',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='assignmenttask',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
