# Generated by Django 2.0 on 2017-12-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_points_or_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon_file_name',
            field=models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='icon_external_url',
            field=models.URLField(max_length=2000, blank=True),
        ),
    ]
