# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 20:11
from __future__ import unicode_literals

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='primary_hex_color',
            field=models.CharField(default='#0062b2', max_length=7, validators=[course.models.validate_hex_color]),
        ),
        migrations.AddField(
            model_name='course',
            name='secondary_hex_color',
            field=models.CharField(default='#ff9800', max_length=7, validators=[course.models.validate_hex_color]),
        ),
    ]
