# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-29 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('course', '0011_post_is_draft'),
    ]
    
    operations = [
        migrations.RemoveField(
            model_name='task',
            name='enabled_from',
        ),
        migrations.RemoveField(
            model_name='task',
            name='enabled_until',
        ),
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, unique=False),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('name', 'course')]),
        ),
    ]
