# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-28 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_add_course_class_to_assignment_task_step_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('markdown_text', models.TextField()),
                ('html_code', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseClass')),
            ],
        ),
    ]
