# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-13 13:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_widget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Canceled')),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_file_name', models.ImageField(blank=True, upload_to='')),
                ('icon_external_url', models.URLField(blank=True, max_length=2000)),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ClassBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Badge')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseClass')),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='class_badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.ClassBadge'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='classbadge',
            unique_together=set([('badge', 'course_class')]),
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together=set([('course', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together=set([('enrollment', 'class_badge')]),
        ),
    ]
