# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-05 21:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBadgeCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('goal_type', models.CharField(choices=[('PERCENTAGE', 'percentage'), ('XP', 'xp')], default='PERCENTAGE', max_length=10)),
                ('accepts_partial_goal', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Assignment')),
            ],
        ),
        migrations.AddField(
            model_name='classbadge',
            name='aggregation_type_for_criteria',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=3),
        ),
        migrations.AddField(
            model_name='classbadgecriteria',
            name='class_badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.ClassBadge'),
        ),
        migrations.AddField(
            model_name='classbadgecriteria',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Task'),
        ),
    ]
