# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-06 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_badge_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='classbadge',
            name='show_info_before_completion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classbadge',
            name='show_progress',
            field=models.BooleanField(default=True),
        ),
    ]
