# Generated by Django 5.0.2 on 2024-02-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_alter_courseclass_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='html_code',
        ),
    ]
