# Generated by Django 5.0.2 on 2024-02-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_courseclass_total_of_lives_enrollment_lost_lives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
