# Generated by Django 5.0.2 on 2024-02-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
