# Generated by Django 5.0.1 on 2024-02-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_alter_courseclass_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmenttask',
            options={'permissions': [('add_assignmenttask_to_my_classes', 'Can add assignment task to my classes'), ('change_assignmenttask_from_my_classes', 'Can change assignment task from my classes'), ('view_assignmenttask_from_my_classes', 'Can view assignment task from my classes'), ('delete_assignmenttask_from_my_classes', 'Can delete assignment task from my classes')], 'verbose_name': 'Assignment Task', 'verbose_name_plural': 'Assignment Tasks'},
        ),
        migrations.AlterModelOptions(
            name='classbadge',
            options={'permissions': [('add_classbadge_to_my_classes', 'Can add class badge to my classes'), ('change_classbadge_from_my_classes', 'Can change class badge from my classes'), ('view_classbadge_from_my_classes', 'Can view class badge from my classes'), ('delete_classbadge_from_my_classes', 'Can delete class badge from my classes')]},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'permissions': [('add_enrollment_to_my_classes', 'Can add enrollment to my classes'), ('change_enrollment_from_my_classes', 'Can change enrollment from my classes'), ('view_enrollment_from_my_classes', 'Can view enrollment from my classes'), ('delete_enrollment_from_my_classes', 'Can delete enrollment from my classes')]},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('add_post_to_my_classes', 'Can add post to my classes'), ('change_post_from_my_classes', 'Can change post from my classes'), ('view_post_from_my_classes', 'Can view post from my classes'), ('delete_post_from_my_classes', 'Can delete post from my classes')]},
        ),
        migrations.AlterModelOptions(
            name='widget',
            options={'permissions': [('add_widget_to_my_classes', 'Can add widget to my classes'), ('change_widget_from_my_classes', 'Can change widget from my classes'), ('view_widget_from_my_classes', 'Can view widget from my classes'), ('delete_widget_from_my_classes', 'Can delete widget from my classes')]},
        ),
    ]
