# Generated by Django 5.0.1 on 2024-02-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_add_custom_permission_for_instructors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['course__code', 'name']},
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['course__code', 'name']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code', 'name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['course__code', 'name']},
        ),
    ]
