# Generated by Django 5.0.1 on 2024-02-29 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_alter_ordering_in_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name']},
        ),
    ]
