# Generated by Django 5.2.5 on 2025-08-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_alter_student_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
